### ISSUE TITLE
Website crashes under certain condition

### ISSUE THREAD

**Issue by BenjaminMichaelis** [dbis-uibk/relax#167] opened 2022-02-23 07:16 UTC
Under certain query, when clicking on the relational tree, the site just goes blank and requires a reload.

![tempppppp](https://user-images.githubusercontent.com/22186029/155275563-4f6a32ab-e9e7-42aa-b0de-1a6e1af06a39.gif)

**Comment by r-prem** [comment] 2022-07-22 12:13
@BenjaminMichaelis Can you provide the gist / dataset in which this is occurring?

**Comment by BenjaminMichaelis** [comment] 2022-07-25 21:32
I have looked around a bit and will look more, but used many gists around this time and am not sure exactly which one I used to cause this problem...

**Comment by r-prem** [comment] 2022-08-05 13:03
Alright, I'm closing the issue as I cannot reproduce it.

**Closed as not planned by r-prem** 2022-08-05 13:03 UTC
Labels: bug, in progress
