### ISSUE TITLE
Export execution plan tree to file

### ISSUE THREAD

**Issue by evazangerle** [dbis-uibk/relax#46] opened 2020-02-04 18:40 UTC
Instead of having to take a screenshot of the execution plan, it would be convenient to be able to export the tree to e.g., some image format or pdf.

**Comment by michaelrampl** [comment] 2020-02-10 09:03
Related to #50

**Comment by michaelrampl** [comment] 2020-09-22 04:46
duplicate of #50

**Closed as completed by michaelrampl** 2020-09-22 04:46 UTC
Labels: feature, low-priority
