### ISSUE TITLE
SQL conversion to relational algebra not working for this SELECT statement

### ISSUE THREAD

**Issue by AxelTuomi** [dbis-uibk/relax#66] opened 2020-02-17 10:45 UTC
This SQL script is not converting to a functioning relational algebra statement: `select distinct teaches.course_id from teaches join instructor on instructor.ID = teaches.ID where instructor.name = 'Brandt'`. This statement was used on the Silberschatz - UniversityDB database and works perfectly fine but when it is converted to relational algebra it returns a error, this is the relational algebra statement it returns: π teaches.course_id σ instructor.name = 'Brandt' teaches ⨝ instructor.ID = teaches.ID instructor. Here is the error: Error: could not find column "instructor.name" in schema [teaches.ID : number, teaches.course_id : string, teaches.sec_id : number, teaches.semester : string, teaches.year : number].

**Comment by immutablestate** [comment] 2020-02-18 09:21
Hi!

Thank you for reporting that issue. The problem is that RelaX does not correctly parenthesize the join. The correct relational algebra expression would be

`π teaches.course_id σ instructor.name = 'Brandt' (teaches ⨝ instructor.ID = teaches.ID instructor)`

We will fix this as soon as possible.

**Comment by michaelrampl** [comment] 2020-05-24 18:52
fixed with 94565fa

**Comment by michaelrampl** [comment] 2020-05-24 18:53
![image](https://user-images.githubusercontent.com/60225162/82762320-91b57b80-9e00-11ea-93f1-7881748b3840.png)

**Closed as completed by michaelrampl** 2020-05-24 18:52 UTC
Labels: bug, high-priority

**Comment by tommyhawkdev** [comment] 2020-09-28 15:52
Hi. i have same problem. here is the sql statement: `select distinct student.ID from (student join takes using (ID)) join (instructor join teaches using(ID)) using (course_id, sec_id, semester, year) where instructor.name = 'Einstein'` This statement was used on the Silberschatz - UniversityDB. it works on SQL tabs but when i try to execute the relational algebra result : `π student.ID σ instructor.name = 'Einstein' ( ( student ⨝ takes ) ⨝ ( instructor ⨝ teaches ) ) `  it will return an error.
here is the error : Error: could not find column "instructor.name" in schema [student.ID : number, student.name : string, student.dept_name : string, student.tot_cred : number, takes.course_id : string, takes.sec_id : number, takes.semester : string, takes.year : number, takes.grade : string, instructor.salary : number]
